import type { TourDefinition } from "./types"

export const pollerTour: TourDefinition = {
  id: "poller",
  label: "REST API Poller Tutorial",
  description: "Learn how to build a connector that polls a REST API on a schedule.",
  connectorKind: "RestApiPoller",
  stops: [
    {
      id: "poller-kind",
      elementSelector: "[data-tutorial='kind-RestApiPoller']",
      stepId: "basics",
      mode: "connector",
      title: "Select Connector Type",
      description: "A REST API Poller connector lets Microsoft Sentinel poll a REST API on a schedule to pull data in. Click the REST API Poller button to select it, then click Next.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "poller-title",
      elementSelector: "#title",
      stepId: "basics",
      mode: "connector",
      title: "Connector Title",
      description: "This is the display name users see in the Sentinel Data Connector gallery. Type \"Contoso Security Alerts (API)\" to continue.",
      expectedValue: "Contoso Security Alerts (API)",
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "poller-connectorId",
      elementSelector: "#connectorId",
      stepId: "basics",
      mode: "connector",
      title: "Connector ID (Auto-generated)",
      description: "The Connector ID is automatically derived from the title. It's used as the internal ARM resource name.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "poller-publisher",
      elementSelector: "#publisher",
      stepId: "basics",
      mode: "connector",
      title: "Publisher Name",
      description: "This identifies who built the connector. Type \"Contoso Ltd.\" to continue.",
      expectedValue: "Contoso Ltd.",
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "poller-description",
      elementSelector: "#description",
      stepId: "basics",
      mode: "connector",
      title: "Connector Description",
      description: "Describe what data this connector ingests. Start your description with \"Ingests\" (e.g., \"Ingests security events from the Contoso API\").",
      expectedValue: "Ingests",
      matchStrategy: "startsWith",
      side: "top",
    },
    {
      id: "poller-authType",
      elementSelector: "[data-tutorial='auth-type']",
      stepId: "api-config",
      mode: "connector",
      title: "Authentication Type",
      description: "Choose how Sentinel authenticates with the API. Select \"API Key\" for this tutorial — it's the simplest auth method where an API key is passed in a header. Then click Next.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "poller-apiEndpoint",
      elementSelector: "#apiEndpoint",
      stepId: "api-config",
      mode: "connector",
      title: "API Endpoint URL",
      description: "The REST API endpoint that Sentinel will poll. Type \"https://api.contoso.com/v1/alerts\" to continue.",
      expectedValue: "https://api.contoso.com/v1/alerts",
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "poller-httpMethod",
      elementSelector: "[data-tutorial='http-method']",
      stepId: "api-config",
      mode: "connector",
      title: "HTTP Method",
      description: "Most REST APIs use GET for fetching data. This is usually the correct choice. Click Next to continue.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "poller-eventsJsonPaths",
      elementSelector: "[data-tutorial='events-json-paths']",
      stepId: "api-config",
      mode: "connector",
      title: "Events JSON Path",
      description: "This tells Sentinel where to find the array of events in the API response. For example, if the API returns { \"data\": [...] }, the path would be \"$.data\". Click Next to continue.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "poller-paging",
      elementSelector: "[data-tutorial='paging-type']",
      stepId: "api-config",
      mode: "connector",
      title: "Pagination",
      description: "If the API returns paginated results, configure the paging strategy here. Many APIs use LinkHeader or NextPageUrl pagination. Click Next to continue.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "top",
    },
    {
      id: "poller-tableName",
      elementSelector: "#tableName",
      stepId: "schema",
      mode: "connector",
      title: "Table Name",
      description: "The Log Analytics table where polled data lands. Custom tables must end with \"_CL\". The auto-derived name is usually fine. Click Next to continue.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "poller-columns",
      elementSelector: "[data-tutorial='column-editor']",
      stepId: "schema",
      mode: "connector",
      title: "Table Columns",
      description: "Define columns to match the fields in your API response. You can paste a sample JSON response to auto-generate columns. Click Next to continue.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "top",
    },
    {
      id: "poller-streamName",
      elementSelector: "#streamName",
      stepId: "dcr",
      mode: "connector",
      title: "Stream Name (Auto-derived)",
      description: "The stream name connects the Data Collection Rule to your table. It's auto-derived from the table name.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "poller-transform",
      elementSelector: "[data-tutorial='kql-editor']",
      stepId: "dcr",
      mode: "connector",
      title: "KQL Transform",
      description: "The transform processes polled data before storage. The default adds a TimeGenerated timestamp. Click Next to continue.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "top",
    },
    {
      id: "poller-connectorUI",
      elementSelector: "[data-tutorial='connector-ui-section']",
      stepId: "connector-ui",
      mode: "connector",
      title: "Connector UI Configuration",
      description: "This configures the connector page in the Sentinel portal. Defaults are auto-generated for your poller connector, including API key setup instructions. Click Next to continue.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "top",
    },
    {
      id: "poller-content",
      elementSelector: "[data-tutorial='content-section']",
      stepId: "content",
      mode: "solution",
      title: "Solution Content (Optional)",
      description: "Optionally bundle analytic rules, hunting queries, ASIM parsers, and workbooks. These enhance your solution but are not required. Click Next to continue.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "top",
    },
    {
      id: "poller-publisherId",
      elementSelector: "#publisherId",
      stepId: "solution",
      mode: "solution",
      title: "Publisher ID",
      description: "A lowercase identifier for your organization. Type \"contoso\" to continue.",
      expectedValue: "contoso",
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "poller-offerId",
      elementSelector: "#offerId",
      stepId: "solution",
      mode: "solution",
      title: "Offer ID",
      description: "A unique lowercase identifier for this solution. Type \"contoso-security-api\" to continue.",
      expectedValue: "contoso-security-api",
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "poller-version",
      elementSelector: "#version",
      stepId: "solution",
      mode: "solution",
      title: "Solution Version",
      description: "Semantic version for your solution. Confirm by typing \"1.0.0\".",
      expectedValue: "1.0.0",
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "poller-supportName",
      elementSelector: "#supportName",
      stepId: "solution",
      mode: "solution",
      title: "Support Contact Name",
      description: "Type \"Contoso Support\" to continue.",
      expectedValue: "Contoso Support",
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "poller-supportEmail",
      elementSelector: "#supportEmail",
      stepId: "solution",
      mode: "solution",
      title: "Support Email",
      description: "Type \"support@contoso.com\" to continue.",
      expectedValue: "support@contoso.com",
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "poller-export",
      elementSelector: "[data-tutorial='export-section']",
      stepId: "export",
      mode: "solution",
      title: "Export Your Solution",
      description: "Congratulations! You've configured a REST API Poller connector. Download the solution ZIP to get all ARM resource files ready for deployment.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "top",
    },
  ],
}
