import type { TourDefinition } from "./types"

export const pushTour: TourDefinition = {
  id: "push",
  label: "Push Connector Tutorial",
  description: "Learn how to build a Push connector that receives data from your application.",
  connectorKind: "Push",
  stops: [
    {
      id: "push-kind",
      elementSelector: "[data-tutorial='kind-Push']",
      stepId: "basics",
      mode: "connector",
      title: "Connector Type: Push",
      description: "A Push connector lets your application send data directly to the Microsoft Sentinel ingestion endpoint. This is already selected for you. Click Next to continue.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "push-title",
      elementSelector: "#title",
      stepId: "basics",
      mode: "connector",
      title: "Connector Title",
      description: "This is the display name users see in the Sentinel Data Connector gallery. Type \"Contoso Security Alerts\" to continue.",
      expectedValue: "Contoso Security Alerts",
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "push-connectorId",
      elementSelector: "#connectorId",
      stepId: "basics",
      mode: "connector",
      title: "Connector ID (Auto-generated)",
      description: "The Connector ID is automatically derived from the title. It's used as the internal ARM resource name. You can override it if needed, but the auto-derived value is usually fine.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "push-publisher",
      elementSelector: "#publisher",
      stepId: "basics",
      mode: "connector",
      title: "Publisher Name",
      description: "This identifies who built the connector. It appears in the connector gallery. Type \"Contoso Ltd.\" to continue.",
      expectedValue: "Contoso Ltd.",
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "push-description",
      elementSelector: "#description",
      stepId: "basics",
      mode: "connector",
      title: "Connector Description",
      description: "Describe what data this connector ingests. Supports Markdown. Start your description with \"Ingests\" (e.g., \"Ingests security alert events from Contoso\").",
      expectedValue: "Ingests",
      matchStrategy: "startsWith",
      side: "top",
    },
    {
      id: "push-tableName",
      elementSelector: "#tableName",
      stepId: "schema",
      mode: "connector",
      title: "Table Name",
      description: "This is the Log Analytics table where your data lands. Custom tables must end with \"_CL\". Type \"ContosoSecurityAlerts_CL\" to continue.",
      expectedValue: "ContosoSecurityAlerts_CL",
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "push-columns",
      elementSelector: "[data-tutorial='column-editor']",
      stepId: "schema",
      mode: "connector",
      title: "Table Columns",
      description: "Every table gets a TimeGenerated column automatically. You can add more columns to match your event schema. You can also paste a sample JSON event to auto-generate columns. Click Next to continue.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "top",
    },
    {
      id: "push-streamName",
      elementSelector: "#streamName",
      stepId: "dcr",
      mode: "connector",
      title: "Stream Name (Auto-derived)",
      description: "The stream name is derived from your table name. Your application uses this when sending data to the ingestion endpoint. It follows the format Custom-<TableName>.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "push-transform",
      elementSelector: "[data-tutorial='kql-editor']",
      stepId: "dcr",
      mode: "connector",
      title: "KQL Transform",
      description: "The Data Collection Rule (DCR) transform is a KQL query that processes incoming data before it's stored. The default transform passes data through and adds a TimeGenerated timestamp. Click Next to continue.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "top",
    },
    {
      id: "push-connectorUI",
      elementSelector: "[data-tutorial='connector-ui-section']",
      stepId: "connector-ui",
      mode: "connector",
      title: "Connector UI Configuration",
      description: "This section configures what users see when they open your connector in the Sentinel portal: graph queries, sample queries, permissions, and instruction steps. Defaults are auto-generated based on your connector settings. Click Next to continue.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "top",
    },
    {
      id: "push-content",
      elementSelector: "[data-tutorial='content-section']",
      stepId: "content",
      mode: "solution",
      title: "Solution Content (Optional)",
      description: "You can optionally bundle analytic rules, hunting queries, ASIM parsers, and workbooks with your solution. These are not required for a basic connector. Click Next to continue.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "top",
    },
    {
      id: "push-publisherId",
      elementSelector: "#publisherId",
      stepId: "solution",
      mode: "solution",
      title: "Publisher ID",
      description: "A lowercase identifier for your organization in the Content Hub. Type \"contoso\" to continue.",
      expectedValue: "contoso",
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "push-offerId",
      elementSelector: "#offerId",
      stepId: "solution",
      mode: "solution",
      title: "Offer ID",
      description: "A unique lowercase identifier for this solution package. Type \"contoso-security-alerts\" to continue.",
      expectedValue: "contoso-security-alerts",
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "push-version",
      elementSelector: "#version",
      stepId: "solution",
      mode: "solution",
      title: "Solution Version",
      description: "Semantic version for your solution package. The default \"1.0.0\" is fine for a new solution. Confirm by typing \"1.0.0\".",
      expectedValue: "1.0.0",
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "push-supportName",
      elementSelector: "#supportName",
      stepId: "solution",
      mode: "solution",
      title: "Support Contact Name",
      description: "The support contact name shown to users of your solution. Type \"Contoso Support\" to continue.",
      expectedValue: "Contoso Support",
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "push-supportEmail",
      elementSelector: "#supportEmail",
      stepId: "solution",
      mode: "solution",
      title: "Support Email",
      description: "The support email address for your solution. Type \"support@contoso.com\" to continue.",
      expectedValue: "support@contoso.com",
      matchStrategy: "exact",
      side: "bottom",
    },
    {
      id: "push-export",
      elementSelector: "[data-tutorial='export-section']",
      stepId: "export",
      mode: "solution",
      title: "Export Your Solution",
      description: "Congratulations! You've configured a Push connector. From here you can download the solution ZIP containing all ARM resource files, ready for the Azure Sentinel packaging tool or direct deployment.",
      expectedValue: null,
      matchStrategy: "exact",
      side: "top",
    },
  ],
}
